import type { Product } from '../src/types.js';

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: 'prod-charizard-199',
    name: '2023 Pokémon Charizard ex #199 Special Illustration Rare',
    slug: 'pokemon-charizard-ex-199-sir-scarlet-violet-151',
    sku: 'CV-PKM-CHZ199',
    categoryId: 'cat-pokemon',
    productType: 'Single Card',
    brand: 'Pokémon',
    series: 'Scarlet & Violet: 151',
    price: 15999,
    salePrice: 14499,
    stock: 4,
    lowStockThreshold: 2,
    condition: 'Near Mint',
    gradingStatus: 'Raw / Authenticated',
    finish: 'Holo / Foil',
    rarity: 'Special Illustration Rare',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'The pinnacle chase card of the English 151 expansion. Features Charizard ascending in hyper-detailed fiery relief. Inspected under high-intensity ultraviolet and 10x magnification at CardVault Mumbai. Centering is mathematically sound (55/45) with pristine holographic surface clarity.',
    specifications: {
      'Card Number': '199/165',
      'Language': 'English',
      'Release Year': '2023',
      'Card Finish': 'Textured Full Art Holofoil',
      'Vault Authentication': 'CardVault Tamper-Proof Hologram Included',
      'Sleeve Standard': 'Dragon Shield Perfect Fit + Ultra Pro Pro-Mold Magnetic Slab'
    },
    createdAt: '2026-03-01T10:00:00.000Z',
    updatedAt: '2026-03-01T10:00:00.000Z'
  },
  {
    id: 'prod-umbreon-vmax-alt',
    name: '2021 Pokémon Umbreon VMAX #215 Alternate Art Secret Rare',
    slug: 'pokemon-umbreon-vmax-215-alt-art-evolving-skies-psa10',
    sku: 'CV-PKM-UMB215',
    categoryId: 'cat-pokemon',
    productType: 'Single Card',
    brand: 'Pokémon',
    series: 'Sword & Shield: Evolving Skies',
    price: 79999,
    salePrice: 74999,
    stock: 1,
    lowStockThreshold: 1,
    condition: 'Gem Mint',
    gradingStatus: 'PSA 10 (Gem Mint)',
    finish: 'Secret Rare Holo',
    rarity: 'Secret Rare Alt Art',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Affectionately known throughout global collecting circles as the "Moonbreon". Encased in an uncirculated PSA 10 Gem Mint certification holder. Iconic artwork depicting Umbreon reaching for the luminous celestial moon. Pristine corners, immaculate gloss, and zero print lines.',
    specifications: {
      'Card Number': '215/203',
      'Grading Authority': 'PSA (Professional Sports Authenticator)',
      'Grade': '10 GEM MINT',
      'Certification Number': 'PSA-89421098',
      'Language': 'English',
      'Release Year': '2021'
    },
    createdAt: '2026-03-02T11:00:00.000Z',
    updatedAt: '2026-03-02T11:00:00.000Z'
  },
  {
    id: 'prod-pkm-151-booster-box',
    name: '2023 Pokémon Scarlet & Violet 151 Factory Sealed Booster Box',
    slug: 'pokemon-151-booster-box-factory-sealed-japanese',
    sku: 'CV-PKM-151BB',
    categoryId: 'cat-sealed',
    productType: 'Booster Box',
    brand: 'Pokémon',
    series: 'Scarlet & Violet: 151 (Japanese)',
    price: 17999,
    salePrice: 16499,
    stock: 6,
    lowStockThreshold: 2,
    condition: 'Factory Sealed',
    gradingStatus: 'Raw / Authenticated',
    finish: 'Factory Shrink Wrap with PokeBall Seal',
    rarity: 'Sealed Collector Display',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Direct imported from Japan. Features unbroken, authentic PokeBall holographic shrink wrap. Contains 20 factory sealed booster packs with 7 cards per pack, including guaranteed Secret Rares and Master Ball mirror reverse holos.',
    specifications: {
      'Pack Count': '20 Booster Packs per Box',
      'Condition': 'Factory Sealed with Pokémon Logo Shrink',
      'Weight Verified': 'Verified in CardVault weigh chamber',
      'Country of Origin': 'Japan',
      'Release Year': '2023'
    },
    createdAt: '2026-03-03T12:00:00.000Z',
    updatedAt: '2026-03-03T12:00:00.000Z'
  },
  {
    id: 'prod-onepiece-luffy-manga',
    name: '2023 One Piece Card Game Monkey D. Luffy #OP05-119 Manga Rare',
    slug: 'one-piece-monkey-d-luffy-manga-rare-op05-psa10',
    sku: 'CV-OP-LFF05',
    categoryId: 'cat-anime',
    productType: 'Single Card',
    brand: 'Bandai',
    series: 'Awakening of the New Era [OP-05]',
    price: 185000,
    salePrice: 179000,
    stock: 1,
    lowStockThreshold: 1,
    condition: 'Gem Mint',
    gradingStatus: 'PSA 10 (Gem Mint)',
    finish: 'Manga Foil / Textured Gold Stamp',
    rarity: 'Secret Manga Alternate Art',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'The crowning grail of the modern One Piece Card Game era. Depicts Eiichiro Oda\'s iconic Gear 5 Luffy awakening with authentic manga panel embossing and iridescent silver foil finish. Graded PSA 10 Gem Mint.',
    specifications: {
      'Card Number': 'OP05-119',
      'Rarity': 'Secret Rare (Manga Alternate Art)',
      'Grading Authority': 'PSA (Gem Mint 10)',
      'Language': 'English',
      'Release Year': '2023'
    },
    createdAt: '2026-03-04T13:00:00.000Z',
    updatedAt: '2026-03-04T13:00:00.000Z'
  },
  {
    id: 'prod-topps-virat-kohli',
    name: '2023 Topps Chrome Virat Kohli #VK18 Master Class Holo',
    slug: 'topps-chrome-cricket-virat-kohli-vk18-master-class',
    sku: 'CV-SPT-VK18',
    categoryId: 'cat-sports',
    productType: 'Single Card',
    brand: 'Topps',
    series: 'Topps Chrome Cricket Elite',
    price: 12999,
    salePrice: 11499,
    stock: 3,
    lowStockThreshold: 2,
    condition: 'Gem Mint',
    gradingStatus: 'Raw / Authenticated',
    finish: 'Refractor / Chrome Holo',
    rarity: 'Ultra Rare Insert',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'The King of Indian Cricket captured in luminous Topps Chrome refractor technology. Celebrating his milestone international centuries. Sharp 90-degree corners, razor-straight edges, and immaculate mirror-like surface reflection.',
    specifications: {
      'Card Number': 'MC-18',
      'Player': 'Virat Kohli',
      'Team': 'India Men\'s National Cricket Team',
      'Finish': 'Prismatic Chrome Refractor',
      'Protection': 'Armored 35pt Magnetic Slab Holder'
    },
    createdAt: '2026-03-05T14:00:00.000Z',
    updatedAt: '2026-03-05T14:00:00.000Z'
  },
  {
    id: 'prod-panini-messi-prizm',
    name: '2020 Panini Prizm Lionel Messi #8 Silver Prizm (Argentina)',
    slug: 'panini-prizm-lionel-messi-8-silver-prizm-psa9',
    sku: 'CV-SPT-MES08',
    categoryId: 'cat-sports',
    productType: 'Single Card',
    brand: 'Panini',
    series: 'Panini Prizm FIFA World Cup Collection',
    price: 26999,
    salePrice: 24999,
    stock: 2,
    lowStockThreshold: 1,
    condition: 'Mint',
    gradingStatus: 'PSA 9 (Mint)',
    finish: 'Silver Prizm Light Refractor',
    rarity: 'Prizm Refractor',
    isFeatured: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'An iconic modern soccer card showcasing Lionel Messi captaining the Albiceleste. Graded PSA 9 Mint. Brilliant rainbow silver refraction with crisp centering and deep cobalt framing.',
    specifications: {
      'Player': 'Lionel Messi',
      'Team': 'Argentina',
      'Grade': 'PSA 9 MINT',
      'Certification': 'PSA-72948190',
      'Release Year': '2020'
    },
    createdAt: '2026-03-06T15:00:00.000Z',
    updatedAt: '2026-03-06T15:00:00.000Z'
  },
  {
    id: 'prod-onepiece-op05-box',
    name: '2023 One Piece Awakening of the New Era (OP-05) Sealed Booster Box',
    slug: 'one-piece-awakening-new-era-op05-sealed-booster-box',
    sku: 'CV-OP-OP05BB',
    categoryId: 'cat-sealed',
    productType: 'Booster Box',
    brand: 'Bandai',
    series: 'One Piece Card Game [OP-05]',
    price: 18499,
    salePrice: 17299,
    stock: 5,
    lowStockThreshold: 2,
    condition: 'Factory Sealed',
    gradingStatus: 'Raw / Authenticated',
    finish: 'Bandai Official Factory Shrink',
    rarity: 'Factory Display Box',
    isFeatured: true,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'The highest demand sealed booster box in modern anime card history. Contains 24 packs with chances to pull the legendary Gear 5 Manga Luffy, Trafalgar Law, and Eustass Kid alternate arts. 100% factory original Bandai seal guaranteed.',
    specifications: {
      'Pack Count': '24 Booster Packs',
      'Cards Per Pack': '12 Cards',
      'Language': 'English',
      'Condition': 'Guaranteed Untampered Factory Shrink',
      'Origin': 'Bandai Namco'
    },
    createdAt: '2026-03-07T16:00:00.000Z',
    updatedAt: '2026-03-07T16:00:00.000Z'
  },
  {
    id: 'prod-pkm-miraidon-deck',
    name: '2024 Pokémon TCG Miraidon ex Deluxe Battle Deck',
    slug: 'pokemon-miraidon-ex-deluxe-battle-deck-sealed',
    sku: 'CV-PKM-MRDDK',
    categoryId: 'cat-decks',
    productType: 'Card Deck',
    brand: 'Pokémon',
    series: 'Scarlet & Violet Competitive',
    price: 2699,
    salePrice: 2399,
    stock: 8,
    lowStockThreshold: 3,
    condition: 'Factory Sealed',
    gradingStatus: 'Raw / Authenticated',
    finish: 'Foil Promo + Standard Deck',
    rarity: 'Competition Starter Set',
    isFeatured: false,
    status: 'published',
    images: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=1000&q=80'
    ],
    description: 'Tournament-ready 60-card electric acceleration deck centered on Miraidon ex, Regieleki VMAX, and Flaaffy. Comes equipped with official foil deck box, damage counters, condition markers, and rulebook.',
    specifications: {
      'Card Count': '60 Authentic Tournament Legal Cards',
      'Includes': 'Deck Box, Metallic Coin, Damage Counters',
      'Condition': 'Factory Sealed Box',
      'Level': 'Deluxe 3-Flame Competition Tier'
    },
    createdAt: '2026-03-08T17:00:00.000Z',
    updatedAt: '2026-03-08T17:00:00.000Z'
  }
];
